version: '3'
services:
  minio:
    image: quay.io/minio/minio
    restart: always
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: ADMIN
      MINIO_ROOT_PASSWORD: P@ssw0rd
    command: ['server', '/data', '--console-address', ':9090']
  uploadfile:
    image: upload-app
    restart: always
    ports:
      - 3000
    depends_on:
      - minio
    deploy:
      replicas: 5
    volumes:
      - ~/log-uploadfile:/usr/logs

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - uploadfile

